import Head from "next/head";

export default function HeadElement({ text }) {
  return (
    <Head className="quicksand">
      <title>{text}</title>
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://cdn.pixabay.com/photo/2020/01/02/16/38/chatbot-4736275_960_720.png"
      ></link>
    </Head>
  );
}
