import Head from 'next/head';

export default function HeadElement({ text }) {
  return (
    <Head>
      <title>{text}</title>
      <meta name='description' content='Generated by create next app' />
      <link rel="icon" href="https://clipground.com/images/programming-logo-clipart-5.jpg"></link>
    </Head>
  )
}