import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Head from 'next/head';
import Navigation from './headless';
import InferenceMachine from '../components/InferenceMachine';

export default function Home() {
  const route = [
    ['Home', '/'],
    ['Login','/login'],
    ['Register', '/register'],
    ['Dashboard', 'https://react-eyechatbot.vercel.app'],
  ];
  const article = [
    ['Bahaya Penyakit Mata',"https://nextjs.org/docs"],
    ['Penanganan Penyakit Mata?',"https://nextjs.org/learn"],
    ['Dokter Spesialis Penyakit Mata',"https://github.com/vercel/next.js/tree/master/examples"],
    ['Rumah Sakit Penyakit Mata',"https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"],
  ];
  return (
    <div className='bg-white'>
      <Head>
        <title>EyeScreening - Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.pixabay.com/photo/2020/01/02/16/38/chatbot-4736275_960_720.png"></link>
      </Head>
      
      <nav
        style={{position:'fixed'}}
        className='bg-slate-100 fixed flex justify-center m-0 py-1 px-0 top-0 shadow-sm space-x-3 text-dark w-100 z-10'
      >
          {route.map(([title, url]) => (
          <a href={url}
            className="font-medium rounded-lg px-3 py-2 text-gray-700 hover:bg-slate-200 hover:shadow hover:text-gray-900"
          >
            {title}
          </a>
        ))}
      </nav>
      <main className='container flex flex-col' style={{marginTop:'70px'}}>
        <InferenceMachine/>
        <Navigation/>
        <h1 className='font-bold mx-auto my-2 text-2xl'>
          Artikel mengenai<span className='text-blue-500'> penyakit mata</span>
        </h1>
        <div className='grid grid-cols-4 gap-4 mx-3 my-2 mw-w-md'>
          {article.map(([title, url]) => (
            <a href={url} 
              className='border-2 hover:border-blue-400 mx-2 px-3 py-1 rounded-lg text-left'
            >
              <h2 className='text-black text-xl'>{title} &rarr;</h2>
            </a>
          ))}
        </div>
      </main>
    </div>
  )
}
