import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Head from 'next/head';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import InferenceMachine from '../components/InferenceMachine';
import '../styles/Home.module.css';

export default function Home() {
  return (
    <div className='bg-blue-300 m-0 poppins'>

      <Head>
        <title>EyeScreening - Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.pixabay.com/photo/2020/01/02/16/38/chatbot-4736275_960_720.png"></link>
      </Head>
      
      <div className='bg-black poppins text-center text-white w-full'>
        Chatbot Expert System
      </div>
      
      <Navbar/>

      <main className='flex flex-col' style={{paddingTop:'55px'}}>
        <InferenceMachine/>
        <Footer/>
      </main>
    </div>
  )
}
