import React, { useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Head from 'next/head';
import { useRouter } from 'next/router';
import axios from 'axios';
import Navbar from '../components/Navbar';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [emailValidation, setEmailValidation] = useState(true);
  const [passwordValidation, setPasswordValidation] = useState(true);
  const [send, setSend] = useState(false);
  const [error, setError] = useState('');
  const router = useRouter();

  const loginHandler = async (e) => {
    // validation after button was click
    if (!email) { setEmailValidation(false); }
    if (!password) { setPasswordValidation(false); }
    e.preventDefault();
    // send data to server
    await axios.post('http://localhost:5000/api/login', 
      ({
        email,
        password,
      })
    )
    .then((response) => {
      setSend(true);
      // set token on localStorage
      (localStorage.setItem('token', response.data.token));
      router.push('/crud-dashboard');
    })
    .catch((error) => {
      setError(error.message);
    })
  }
  
  return (
    <div className="bg-blue-300 h-screen poppins" >

      <style jsx>{`
      `}</style>

      <Head>
        <title>Login Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="https://clipground.com/images/programming-logo-clipart-5.jpg"></link>
      </Head>

      <Navbar/>

      <main className='flex flex-col mt-0' style={{paddingTop:'55px'}}>
        <div className="flex justify-center">
          <div className='col-md-4'>
            <div className='bg-blue-200 card border-2 rounded shadow-sm'>
              <div className='card-body'>
                <h4 className='font-bold'>Login Admin</h4>
                <hr/>
                <form onSubmit={loginHandler}>
                  <div className='mb-3'>
                    <label className='form-label'>Email</label>
                    <input 
                      type='email' 
                      className='form-control' 
                      value={email} 
                      onChange={(e) => {
                        setEmail(e.target.value);
                        setEmailValidation(true);
                        setSend(false);
                        setError('');
                      }}
                      placeholder='Masukkan Alamat Email'
                    />
                  </div>
                  {emailValidation === false && (
                    <div className="alert alert-danger">
                      Email harus diisi
                    </div>
                  )}
                  <div className='mb-3'>
                    <label className='form-label'>Password</label>
                    <input 
                      type='password' 
                      className='form-control' 
                      value={password} 
                      onChange={(e) => {
                        setPassword(e.target.value);
                        setPasswordValidation(true);
                        setSend(false);
                        setError('');
                      }} 
                      placeholder='Masukkan Password'
                    />
                  </div>
                  {passwordValidation === false && (
                    <div className="alert alert-danger">
                      Password harus diisi
                    </div>
                  )}
                  <div className='d-grid gap-2'>
                    <button onClick={loginHandler} type='submit' className='btn btn-primary'>
                      MASUK
                    </button>
                  </div>
                  {send === true && (
                    <div className="alert alert-info mt-3">
                      Tunggu sebentar...
                    </div>
                  )}
                  {error === 'Request failed with status code 409' && (
                    <div className="alert alert-danger mt-3">
                      Email terdaftar, tapi password salah.
                    </div>
                  )}
                  {error === 'Request failed with status code 500' && (
                    <div className="alert alert-danger mt-3">
                      Maaf email tidak terdaftar.
                    </div>
                  )}
                  <div className='mt-3'>
                      <p>Belum punya akun? Daftar terlebih dahulu</p>
                  </div>
                  <div className='d-grid gap-2'>
                    <button onClick={() => { router.push('/register') }} className='btn btn-outline-primary'>
                      DAFTAR
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}